[workspace]
resolver = "2"

members = [
    "commons",
    "demo_chart",
    "drawer",
    "drawing_commons",
    "data_set",
    "image_recognition",
    "linear_interpolation",
    "trigonometry",
    "vectors",
    "viewer",
    "web_commons"
]

[profile.release]
lto = true